### ISSUE TITLE
ColoringText(Scene) does not work

### ISSUE THREAD

**Issue by aevedis** [Elteoremadebeethoven/AnimationsWithManim#18]
If I try rendering the scene I get the following error from the console:

`Traceback (most recent call last):
  File "C:\Manim\manim_28aug\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Manim\manim_28aug\manimlib\scene\scene.py", line 53, in __init__
    self.construct()
  File "solow.py", line 49, in construct
    run_time = 0.12
  File "C:\Manim\manim_28aug\manimlib\animation\composition.py", line 34, in __init__
    [anim.mobject for anim in animations]
  File "C:\Manim\manim_28aug\manimlib\animation\composition.py", line 34, in <listcomp>
    [anim.mobject for anim in animations]
AttributeError: type object 'ApplyMethod' has no attribute 'mobject'`

Note: I am using the 28 Aug version.

**Comment by Elteoremadebeethoven** [comment]
What part of
>  I remind you that this course is based on the version of February 3, 2019

is it not clear?
In a few months I will make an update, but in the meantime, if you want to use my course, you have to use the version that I specify.
