### ISSUE TITLE
"latex" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable.

### ISSUE THREAD

**Issue by ErnTreumun** [Elteoremadebeethoven/AnimationsWithManim#23]
Hola! tengo un problema al ejecutar "WriteStuff" cuando instalo manim. Inserto lo que me aparece en la pantalla de cmd
C:\Manim\manim_3_feb>python -m manim example_scenes.py WriteStuff -pl
Writing "\centering This is a some text" to C:\Manim\manim_3_feb\manimlib\files\Tex\fc014450ce29cae4.tex
"latex" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

Traceback (most recent call last):
  File "C:\Manim\manim_3_feb\manimlib\extract_scene.py", line 153, in main
    scene = SceneClass(**scene_kwargs)
  File "C:\Manim\manim_3_feb\manimlib\scene\scene.py", line 54, in __init__
    self.construct()
  File "example_scenes.py", line 100, in construct
    tex_to_color_map={"text": YELLOW}
  File "C:\Manim\manim_3_feb\manimlib\mobject\svg\tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "C:\Manim\manim_3_feb\manimlib\mobject\svg\tex_mobject.py", line 45, in __init__
    self.template_tex_file_body
  File "C:\Manim\manim_3_feb\manimlib\utils\tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "C:\Manim\manim_3_feb\manimlib\utils\tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: C:\Manim\manim_3_feb\manimlib\files\Tex\fc014450ce29cae4.log
Saludos

**Comment by ErnTreumun** [comment]
Solucionado, en mi caso en el "Path" no estaba agregado miktex
tuve que agregarlo a mano escribiendo la linea "C:\Program Files\MiKTeX 2.9\miktex\bin\x64"
