### ISSUE TITLE
Positional arguments are missing (kwargs)

### ISSUE THREAD

**Issue by zdarovakoresh** [Elteoremadebeethoven/AnimationsWithManim#45]
I'm learning Manim through your video tutorial. Thank you for giving us such a great opportunity to learn how to use it.

Currently I'm investigating the making use of arrays (Manim tutorial | 3). Almost every one of 26 classes (FormulaColor1, CrossText, etc) from 3_text_like_arrays.py give an error:

` __init__() missing 1 required positional argument: 'kwargs'`

I suppose some configuration parameters are missing, but I don't know how to set them. I use Win10 x64.

For example, when calling FormulaColor1, which is:

```
class FormulaColor1(Scene): 
    def construct(self):
        text = TexMobject("x","=","{a","\\over","b}")
        text[0].set_color(RED)
        text[1].set_color(BLUE)
        text[2].set_color(GREEN)
        text[3].set_color(ORANGE)
        text[4].set_color("#DC28E2")
        self.play(Write(text))
        self.wait(2)
```

I receive this error:

```
Traceback (most recent call last):
  File "C:\Program Files\Manim\manimlib\extract_scene.py", line 155, in main
    scene = SceneClass()
  File "C:\Program Files\Manim\manimlib\scene\scene.py", line 75, in __init__
    self.construct(**kwargs)
  File "3_text_like_arrays.py", line 26, in construct
    self.play(Write(text))
TypeError: __init__() missing 1 required positional argument: 'kwargs'
```
What is the problem?

**Comment by zdarovakoresh** [comment]
Reinstalling manim solves this.
[See for the details.](https://github.com/3b1b/manim/issues/1191)
